services:
  easytodo:
    image: easy-todo-grocery-nodb:${TAG:-latest}
    build:
      context: ../../..
      dockerfile: docker/v1.0.0/no-db/Dockerfile
    env_file:
      - ../.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - APP_HOST_NAME=${APP_HOST_NAME}
      - APP_HOST_PORT=${APP_HOST_PORT}
      - SOCKETIO_HOST=${SOCKETIO_HOST}
      - SOCKETIO_PORT=${SOCKETIO_PORT}
    ports:
      - "8100:8100"
