name: easy-todo-grocery-nodb
services:
  easytodo:
    image: easy-todo-grocery-nodb
    build:
      context: ../../..
      dockerfile: docker/v1.0.0/no-db/Dockerfile
    env_file:
      - ../no-db/.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SCHEMA=${DB_SCHEMA}
      - APP_HOST_NAME=${APP_HOST_NAME}
      - APP_HOST_PORT=${APP_HOST_PORT}
      - SOCKETIO_HOST=${SOCKETIO_HOST}
      - SOCKETIO_PORT=${SOCKETIO_PORT}
    networks:
      todo_grocery_net:
        ipv4_address: 172.10.0.4
    ports:
      - "8101:8101"

networks:
  todo_grocery_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.10.0.0/24
          gateway: 172.10.0.1
