-- DROP ROLE prod_todo_grocery;

CREATE ROLE prod_todo_grocery WITH
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    INHERIT
    NOLOGIN
    NOREPLICATION
    NOBYPASSRLS
    CONNECTION LIMIT -1;

-- DROP ROLE dev_todo_grocery;
CREATE ROLE dev_todo_grocery WITH
	NOSUPERUSER
	NOCREATEDB
	NOCREATEROLE
	INHERIT
	NOLOGIN
	NOREPLICATION
	NOBYPASSRLS
	CONNECTION LIMIT -1;
